### ISSUE TITLE
添加MAVEN后IntellIj无法执行

### ISSUE THREAD

**Issue by Bigbiglittle** [bitlap/geocoding#1]
请问，我在MAVEN中导入后，intellIj无法执行main方法，剔除后恢复正常，请问是什么情况

**Comment by IceMimosa** [comment]
导包需要加github的repo，不知道你那边导入成功了没有？可否截个图瞅瞅、

**Comment by Bigbiglittle** [comment]
你好：
导了，而且jar包已经下载下来，但是在main方法中Run,IDEA会出现没反应的情况，删掉JAR包就好了




mjl0799@gmail.com
 
发件人： ChenKai
发送时间： 2018-08-09 15:47
收件人： IceMimosa/geocoding
抄送： Bigbiglittle; Author
主题： Re: [IceMimosa/geocoding] 添加MAVEN后IntellIj无法执行 (#1)
导包需要加github的repo，不知道你那边导入成功了没有？可否截个图瞅瞅、

**Comment by IceMimosa** [comment]
你那边要是解决的话就行。不太明白 `删掉jar就正常了` 的含义，方便的话也可以截个IDEA图我瞅瞅。😅

**Comment by Bigbiglittle** [comment]
我的意思是，引入你的JAR包，整个IDEA的project执行Run命令无反应，但是project并不报错，但是删掉你的geocoding的jar包后，Run可以正常执行，不知道你有没有碰到过





mjl0799@gmail.com
 
发件人： ChenKai
发送时间： 2018-08-09 16:18
收件人： IceMimosa/geocoding
抄送： Bigbiglittle; Author
主题： Re: [IceMimosa/geocoding] 添加MAVEN后IntellIj无法执行 (#1)
你那边要是解决的话就行。不太明白 删掉jar就正常了 的含义，方便的话也可以截个IDEA图我瞅瞅。????

**Comment by IceMimosa** [comment]
额。。我这运行倒是很正常、

**Comment by Bigbiglittle** [comment]
maven 执行package时提示：
，仓库里是缺了这个包吗？



mjl0799@gmail.com
 
发件人： ChenKai
发送时间： 2018-08-09 17:33
收件人： IceMimosa/geocoding
抄送： Bigbiglittle; Author
主题： Re: [IceMimosa/geocoding] 添加MAVEN后IntellIj无法执行 (#1)
额。。我这运行倒是很正常、

**Comment by Bigbiglittle** [comment]
sorry,之前下载失败了，我再看看为什么执行没响应好了



mjl0799@gmail.com
 
发件人： mjl0799@gmail.com
发送时间： 2018-08-09 17:51
收件人： IceMimosa/geocoding
主题： Re: Re: [IceMimosa/geocoding] 添加MAVEN后IntellIj无法执行 (#1)
maven 执行package时提示：
，仓库里是缺了这个包吗？



mjl0799@gmail.com
 
发件人： ChenKai
发送时间： 2018-08-09 17:33
收件人： IceMimosa/geocoding
抄送： Bigbiglittle; Author
主题： Re: [IceMimosa/geocoding] 添加MAVEN后IntellIj无法执行 (#1)
额。。我这运行倒是很正常、

**Comment by IceMimosa** [comment]
没事。。因为需要访问github的raw服务。你可以删除你~/.m2下对应的文件，然后重新执行下打包命令试试。

**Comment by monkeydata918** [comment]
![image](https://user-images.githubusercontent.com/33408389/44527135-8e1b2f00-a718-11e8-9139-a2b483f10876.png)

**Comment by monkeydata918** [comment]
解析的有瑕疵    怎么可以修改一下标准化规则
