### ISSUE TITLE
会去掉路名里面的“一”

### ISSUE THREAD

**Issue by DreamerZZYY** [bitlap/geocoding#10]
解析地址“福建福州鼓楼区六一路111号金三桥大厦”这种路名里面带“一”的会将“一”去掉

**Comment by DreamerZZYY** [comment]
![WeChat Image_20200312111043](https://user-images.githubusercontent.com/39548018/76483536-36572c80-6452-11ea-861d-da139ee13e28.jpg)
找到了，是不是这里把中文“一”清洗掉了。这么做的原因是啥？

**Comment by IceMimosa** [comment]
感谢反馈，尴尬，本来想移除中文的横线（ー－—）的，不知为啥输成了一。。
