### ISSUE TITLE
地址库更新问题

### ISSUE THREAD

**Issue by xxzcool** [bitlap/geocoding#136]
地址库能更新一下吗？谢谢

**Comment by IceMimosa** [comment]
@xxzcool 出现什么问题了么？麻烦给个实例我试下，看看淘宝的地址库是不是最新的。

**Comment by xxzcool** [comment]
有些城市新设立了一些区，比如赣州市的新区都找不到或解析出错（请见截图），所以应该是地址库没更新的问题
![2020-11-05_160602](https://user-images.githubusercontent.com/35692288/98214400-68894180-1f81-11eb-84b5-de9e31d3f927.jpg)

**Comment by IceMimosa** [comment]
感谢反馈，这周抽空改下。🤓

**Comment by xxzcool** [comment]
已经改好了吗 @IceMimosa

**Comment by IceMimosa** [comment]
@xxzcool 
* 修复了下赣县区的地址问题
* 章江新区我在地址库没找到，你可以通过API添加自定义的地址定义。

**Comment by xxzcool** [comment]
好的。谢谢！ @IceMimosa
