### ISSUE TITLE
region.dat 信息比较旧

### ISSUE THREAD

**Issue by linweijiang** [bitlap/geocoding#162]
大佬好，在解析 “重庆市开州区南门镇” 时，发现目前的 region.dat 的地址信息比较老，没有 开州区 这个区。
想问一下大佬 region.dat 这个文件是我们自己来维护吗，还是互联网上就能获取到呢？如果从互联网能获取的话能麻烦发一下链接吗？谢谢

**Comment by IceMimosa** [comment]
目前只能在项目里维护，你可以fock一份自己修改，或者着急的话可以使用「自定义地址设置」。

**Comment by linweijiang** [comment]
好的，谢谢大佬
