### ISSUE TITLE
region.dat 地址偏旧，升级到国家标准地址2020版本

### ISSUE THREAD

**Issue by IceMimosa** [bitlap/geocoding#163]
2020版本国标地址库：http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2020/

思路：采用非覆盖方式，与库中的旧地址进行合并。

fix #162

**Comment by TsLenMo** [comment]
我这里有一份全覆盖的 21版国标库，希望能对项目有所帮助
https://cloud.189.cn/web/share?code=yUBjQfYJzQ7n（访问码：9c9w）

**Comment by IceMimosa** [comment]
@TsLenMo 十分感谢，我瞅瞅。感觉有点大，是按照项目的方式生成的`region.dat`么？

**Comment by IceMimosa** [comment]
> 我这里有一份全覆盖的 21版国标库，希望能对项目有所帮助 [https://cloud.189.cn/web/share?code=yUBjQfYJzQ7n（访问码：9c9w）](https://cloud.189.cn/web/share?code=yUBjQfYJzQ7n%EF%BC%88%E8%AE%BF%E9%97%AE%E7%A0%81%EF%BC%9A9c9w%EF%BC%89)

这个文件alias的处理稍微有点问题，我这边借鉴处理下，太感谢了。考虑文件太大，准备暴露手动传参的方式给调用方使用。

**Comment by TsLenMo** [comment]
> @TsLenMo 十分感谢，我瞅瞅。感觉有点大，是按照项目的方式生成的`region.dat`么？

是的，是根据项目方式生成的

**Comment by linweijiang** [comment]
> 
hi~，请问有优化alias了吗，我发现 @TsLenMo 提供的alias稍微跟解析代码的逻辑不是很匹配得上。

**Comment by TsLenMo** [comment]
> > 
> 
> hi~，请问有优化alias了吗，我发现 @TsLenMo 提供的alias稍微跟解析代码的逻辑不是很匹配得上。

目前我没有优化，不知道作者是否有优化过。

**Comment by linweijiang** [comment]
别名问题优化了一版，我本地测没问题，大家可以测测看 @IceMimosa @TsLenMo 
https://cloud.189.cn/web/share?code=UJVBBvARRnaa（访问码：0uho）

**Comment by TsLenMo** [comment]
> 别名问题优化了一版，我本地测没问题，大家可以测测看 @IceMimosa @TsLenMo [https://cloud.189.cn/web/share?code=UJVBBvARRnaa（访问码：0uho）](https://cloud.189.cn/web/share?code=UJVBBvARRnaa%EF%BC%88%E8%AE%BF%E9%97%AE%E7%A0%81%EF%BC%9A0uho%EF%BC%89)

谢谢，你这个包好小。

**Comment by linweijiang** [comment]
> > 别名问题优化了一版，我本地测没问题，大家可以测测看 @IceMimosa @TsLenMo [https://cloud.189.cn/web/share?code=UJVBBvARRnaa（访问码：0uho）](https://cloud.189.cn/web/share?code=UJVBBvARRnaa%EF%BC%88%E8%AE%BF%E9%97%AE%E7%A0%81%EF%BC%9A0uho%EF%BC%89)
> 
> 谢谢，你这个包好小。

跟原有版本一样，只保留了4级地址信息，包就小了~

**Comment by IceMimosa** [comment]
@linweijiang 牛逼了。抱歉比较懒，一直没啥时间。。😂

**Comment by IceMimosa** [comment]
@TsLenMo @linweijiang 感谢两位，最新版本已支持自定义的地址库参数设置。

**Comment by zui-S** [comment]
请问这个dat地址文件是怎么生成的？

**Comment by liucx1201** [comment]
@

> > > 别名问题优化了一个版本，我本地测没问题，大家可以测测看@IceMimosa @TsLenMo [https://cloud.189.cn/web/share?code=UJVBBvARRnaa（访问码：0uho）](https://cloud.189.cn/web/share?code=UJVBBvARRnaa%EF%BC%88%E8%AE%BF%E9%97%AE%E7%A0%81%EF%BC%9A0uho%EF%BC%89)
> > 
> > 
> > 谢谢，你这个包好小。
> 
> 跟原有版本一样，只保留了4级地址信息，包就小了~

大佬，方便提供优化后的sql数据吗？

**Comment by liucx1201** [comment]
> > > 别名问题优化了一个版本，我本地测没问题，大家可以测测看看@IceMimosa @TsLenMo [https://cloud.189.cn/web/share?code=UJVBBvARRnaa（访问码：0uho）](https://cloud.189.cn/web/share?code=UJVBBvARRnaa%EF%BC%88%E8%AE%BF%E9%97%AE%E7%A0%81%EF%BC%9A0uho%EF%BC%89)
> > 
> > 
> > 谢谢，你这个包好小。
> 
> 跟原有版本一样，只保留了4级地址信息，包就小了~

@linweijiang 大佬，方便提供优化后的sql数据吗？
