### ISSUE TITLE
[BUG] 最后无bat文件产生

### ISSUE THREAD

**Issue by Borber** [bitlap/geocoding#164]
![image](https://user-images.githubusercontent.com/30563826/147809521-f20a5350-aea1-4fb3-9e40-35c85ebd9d88.png)
运行皆正常, 但就是最后没有文件产生

**Comment by Borber** [comment]
平台 windows, 绝对地址, 相对地址都试过

**Comment by IceMimosa** [comment]
@Borber 运行的测试目录的代码？

**Comment by IceMimosa** [comment]
@Borber 稍微修了下，pull下代码再试试呢。

**Comment by Borber** [comment]
> @Borber 稍微修了下，pull下代码再试试呢。

正常了, 赞!
