### ISSUE TITLE
如何由唯一城镇来定位

### ISSUE THREAD

**Issue by Borber** [bitlap/geocoding#166]
![QQ截图20220106155405](https://user-images.githubusercontent.com/30563826/148348686-36a39625-1b13-4c74-ba42-3e9cd1aa3d99.png)

灵山镇海榆大道4号绿地城.润园11#楼2单元203

只取一个省的信息, 进行匹配, 最后匹配出来了街道和区的id, 但没有继续匹配上省, 市, 该怎样修改一下代码呢?

**Comment by IceMimosa** [comment]
@Borber 一般如果只有区地址的话可能会存在多个父级地址，如果强行匹配会有歧义，比如`通州区` 可能 `北京` 和 `江苏南通` 都有。当然可以加配置去控制，不严谨的情况的下可以随机匹配一个。

**Comment by IceMimosa** [comment]
不过这里倒是可以优化下，如果存在歧义地址就不匹配，只有一个父地址的话可以匹配一下。。

**Comment by Borber** [comment]
> @Borber 一般如果只有区地址的话可能会存在多个父级地址，如果强行匹配会有歧义，比如`通州区` 可能 `北京` 和 `江苏南通` 都有。当然可以加配置去控制，不严谨的情况的下可以随机匹配一个。

嗯, 就是不需要太严谨的, 因为只拿了一个省的数据, 所以出现多个父级的概率很小

**Comment by Borber** [comment]
> 不过这里倒是可以优化下，如果存在歧义地址就不匹配，只有一个父地址的话可以匹配一下。。

赞👍

**Comment by IceMimosa** [comment]
> > @Borber 一般如果只有区地址的话可能会存在多个父级地址，如果强行匹配会有歧义，比如`通州区` 可能 `北京` 和 `江苏南通` 都有。当然可以加配置去控制，不严谨的情况的下可以随机匹配一个。
> 
> 嗯, 就是不需要太严谨的, 因为只拿了一个省的数据, 所以出现多个父级的概率很小

我看`灵山镇`好像山东也有一个，估计是这个原因导致的。你刚说的限定查询范围倒是一个不错的建议，可以加个配置控制下。

**Comment by Borber** [comment]
> > > @Borber 一般如果只有区地址的话可能会存在多个父级地址，如果强行匹配会有歧义，比如`通州区` 可能 `北京` 和 `江苏南通` 都有。当然可以加配置去控制，不严谨的情况的下可以随机匹配一个。
> > 
> > 
> > 嗯, 就是不需要太严谨的, 因为只拿了一个省的数据, 所以出现多个父级的概率很小
> 
> 我看`灵山镇`好像山东也有一个，估计是这个原因导致的。你刚说的限定查询范围倒是一个不错的建议，可以加个配置控制下。

我其实是直接从 国家数据的表里删除了所有非海南的数据 `delete from cnarea where cnarea.area_code not like "46%"`

**Comment by IceMimosa** [comment]
恩理解，只是在想是否可以融入到通用方案里面。周末试一下 0.0

**Comment by Borber** [comment]
> 恩理解，只是在想是否可以融入到通用方案里面。周末试一下 0.0

大佬周末忙吗, 🤪 , 有没有看一下怎么优化呀.
