### ISSUE TITLE
下载依赖失败

### ISSUE THREAD

**Issue by JohnnyTing** [bitlap/geocoding#167]
通过readme 下载github的repo依赖失败：

Failed to execute goal on project customer-experience-data-factory: Could not resolve dependencies for project com.treeyee.cloud:customer-experience-data-factory:jar:0.0.1-SNAPSHOT: io.patamon.geocoding:geocoding:jar:1.1.6 was not found in https://raw.github.com/icemimosa/maven/release/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of patamon.release.repository has elapsed or updates are forced -> [Help 1]

克隆项目本地编译生成jar包，将jar添加到项目也运行失败（本地项目是java项目）:
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
at io.patamon.geocoding.Geocoding.similarity(Geocoding.kt)

老哥你知道这是啥原因吗

**Comment by IceMimosa** [comment]
@JohnnyTing 下载jar的方式不太好，需要kotlin环境。
删除 `~/.m2/repository/io/patamon/geocoding/geocoding/1.1.6` 目录重新下呢，可能网不好。

**Comment by IceMimosa** [comment]
稍等下，好像确实没法下了。。github真坑，我看下

**Comment by IceMimosa** [comment]
github改了访问机制，需要在申请一个token，勾上跟package相关的选项，参考下README

参考：https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#publishing-a-package

**Comment by JohnnyTing** [comment]
> github改了访问机制，需要在申请一个token，勾上跟package相关的选项，参考下README
> 
> 参考：https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#publishing-a-package

我添加上token还是 下载失败了，你那边删除```~/.m2/repository/io/patamon/geocoding/geocoding/1.1.6``` 后能下载吗，不本地打包的情况下

**Comment by IceMimosa** [comment]
@JohnnyTing 是的，我删除了本地的包，重新从远程下的。你看看这个链接输入用户和token后，能不能访问：https://maven.pkg.github.com/IceMimosa/geocoding/io/patamon/geocoding/geocoding/1.1.6/geocoding-1.1.6.pom

**Comment by JohnnyTing** [comment]
> @JohnnyTing 是的，我删除了本地的包，重新从远程下的。你看看这个链接输入用户和token后，能不能访问：https://maven.pkg.github.com/IceMimosa/geocoding/io/patamon/geocoding/geocoding/1.1.6/geocoding-1.1.6.pom

能访问，就是本地maven下载不了

![image](https://user-images.githubusercontent.com/46625434/149444895-c128cc6b-7ba1-42ca-ad51-a81bfe6743fd.png)

**Comment by IceMimosa** [comment]
@JohnnyTing 地址不是 `raw.github.com` 那个了，换成 `https://maven.pkg.github.com/IceMimosa/geocoding`，看下README，我更新了下，有点小坑。

**Comment by JohnnyTing** [comment]
@IceMimosa 可以了，谢谢老哥

**Comment by xxllp** [comment]
这个项目为啥不能脱离原始的库呢

**Comment by IceMimosa** [comment]
@xxllp 原始的库是指啥0.0

**Comment by xxllp** [comment]
搞错了  我看成python 库了 这个库的数据是从哪里来的 算法是啥

**Comment by IceMimosa** [comment]
@xxllp readme有：https://github.com/IceMimosa/geocoding#21-%E6%A0%87%E5%87%86%E5%9C%B0%E5%9D%80%E5%BA%93

**Comment by xxllp** [comment]
好的   这个原始数据里面没有的其他字段 比如道路名称 编码啥的是怎么匹配出来的呢
