### ISSUE TITLE
使用国标库 标准化没办法到5级

### ISSUE THREAD

**Issue by TsLenMo** [bitlap/geocoding#170]
比如这个地址：东莞市莞城街道罗沙社区东兴路(道路)东兴门诊部1层.
![图片](https://user-images.githubusercontent.com/23328499/160647860-97988ac7-c284-4dcb-bec9-ad00f6faf04c.png)

结果：
```
  Address(
	  provinceId=440000000000, province=广东省, 
	  cityId=441900000000, city=东莞市, 
	  districtId=441900006000, district=莞城街道, 
	  streetId=null, street=null, 
	  townId=null, town=null, 
	  villageId=null, village=null, 
	  road=罗沙社区东兴路, 
	  roadNum=, 
	  buildingNum=null, 
	  text=东兴门诊部1层道路
  )
```

**Comment by IceMimosa** [comment]
@TsLenMo 恩地址偏旧了，确实没有支持「莞城街道」下的乡镇信息。有个issue了 #163，暂时还没空搞。0.0

**Comment by TsLenMo** [comment]
> @TsLenMo 恩地址偏旧了，确实没有支持「莞城街道」下的乡镇信息。有个issue了 #163，暂时还没空搞。0.0

这个是我使用 21 国标库后的
