### ISSUE TITLE
自定义地址时可将错误的地址关联到正确的上面去么？

### ISSUE THREAD

**Issue by cheese8** [bitlap/geocoding#171]
感觉自定义地址是在字典里面新增地址的，而不是用于将错误地址改正后解析的？ @IceMimosa 

举个例子：

Geocoding.addRegionEntry(510000000000L, 100000000000L, "四州省", RegionType.Province, "四川")
Geocoding.normalizing("四州省广安市广安区")

能够将地址正确的解析为：四川省广安市广安区么？

**Comment by IceMimosa** [comment]
@cheese8 这个问题给`四川省`加个别名就好了，你的写反了。

```kotlin
Geocoding.addRegionEntry(510000000000L, 100000000000L, "四川省", RegionType.Province, "四州省")
println(Geocoding.normalizing("四州省广安市广安区"))
```

**Comment by cheese8** [comment]
收到，多谢。
