### ISSUE TITLE
请问下 resources 里的 region.dic 和 community.dic 能否更新，如何生成呢？

### ISSUE THREAD

**Issue by Wanqingling** [bitlap/geocoding#185]
请问下 resources 里的 region.dic 和 community.dic 能否更新，如何生成呢？

**Comment by IceMimosa** [comment]
@Wanqingling 这两个目前仅仅是在算相似度的时候，在IK分词器配置文件IKAnalyzer.cfg.xml中使用。可以在你的classpath下面直接覆盖`dic/region.dic`和`dic/community.dic`这两个文件试试，不行的话，可能需要写点代码自定义一下了

**Comment by Wanqingling** [comment]
> @Wanqingling 这两个目前仅仅是在算相似度的时候，在IK分词器配置文件IKAnalyzer.cfg.xml中使用。可以在你的classpath下面直接覆盖`dic/region.dic`和`dic/community.dic`这两个文件试试，不行的话，可能需要写点代码自定义一下了

好的感谢作者回复，其实我就是看这两个 dic 是七年前更新的，里面的内容可能会有些和现在的地址街道不符合，请问下这两个 dic 文件，尤其是 region.dic 和  region.dat 有什么关系吗？是否可以通过 region_2021.dat 去生成最新的 dic，还是说 dic 只是自己爬虫拿到的一些数据，无法通过 region_2021.dat 生成。（目前我查看了源码暂未找到 region_2021.dat  和 region.dic之间有联系）

**Comment by Wanqingling** [comment]
> @Wanqingling 这两个目前仅仅是在算相似度的时候，在IK分词器配置文件IKAnalyzer.cfg.xml中使用。可以在你的classpath下面直接覆盖`dic/region.dic`和`dic/community.dic`这两个文件试试，不行的话，可能需要写点代码自定义一下了

麻烦作者有空回复下呀，比较着急~~

**Comment by IceMimosa** [comment]
@Wanqingling 对，两者之间没有啥关联。`region.dat`主要用于地址标准化的，之前的`region.dic`好像有部分是通过它生成的，主要用于分词做相似度的，两个文件之间没啥关系。。而且这个dic很多都是爬虫抓取的，里面有很多小区的名称，直接通过dat生成不太行。

**Comment by Wanqingling** [comment]
> @Wanqingling 对，两者之间没有啥关联。`region.dat`主要用于地址标准化的，之前的`region.dic`好像有部分是通过它生成的，主要用于分词做相似度的，两个文件之间没啥关系。。而且这个dic很多都是爬虫抓取的，里面有很多小区的名称，直接通过dat生成不太行。

好的呢，感谢作者解答疑惑~
