### ISSUE TITLE
寻找志愿者维护项目

### ISSUE THREAD

**Issue by jxnu-liguobin** [bitlap/geocoding#192]
要求：
1. 熟悉Kotlin、Java
2. 熟悉github上的开源协作和版本控制

**Comment by anqihui** [comment]
我我我

**Comment by jxnu-liguobin** [comment]
> anqihui

好，那你先捋捋代码，我给你发邀请

**Comment by anqihui** [comment]
okok

**Comment by jxnu-liguobin** [comment]
> okok

看看邮件，已经发了
<img width="530" alt="image" src="https://github.com/bitlap/geocoding/assets/29496873/023309d7-fe46-47df-bca1-85dbb5476dda">

**Comment by jxnu-liguobin** [comment]
@anqihui 尽量不要直接push master，通过PR提交，合并时选择Squash

**Comment by anqihui** [comment]
好的
