### ISSUE TITLE
解析地址时buildingNum出现null，怎样修改相关规则，谢谢大神！！

### ISSUE THREAD

**Issue by monkeydata918** [bitlap/geocoding#3]
Address(
	provinceId=110000000000, province=北京, 
	cityId=110100000000, city=北京市, 
	districtId=110102000000, district=西城区, 
	streetId=null, street=null, 
	townId=null, town=null, 
	villageId=null, village=null, 
	road=新康街, 
	roadNum=2号院, 
	buildingNum=null, 
	text=1号楼北侧楼房
)

**Comment by IceMimosa** [comment]
emmmm，我试试哈。

**Comment by IceMimosa** [comment]
目前还没法定制，有空我重构下。
这个问题我刚刚修复了下（将 `1号楼` 提取到了 buildingNum 中），请使用1.1.1版本。
另外，欢迎提供更多的错误案例给我，谢谢。🤣

**Comment by monkeydata918** [comment]
很无奈是kotlin写的 我现在正在改 但速度很慢  如果可以会给楼主更多的案例    谢谢

**Comment by IceMimosa** [comment]
哈哈哈，kotlin大法好。。有啥问题随时骚扰

**Comment by monkeydata918** [comment]
在下佩服  好的    感谢
