### ISSUE TITLE
多个匹配结果返回的问题

### ISSUE THREAD

**Issue by ghost** [bitlap/geocoding#5]
比如输入“南山区”，会有两个匹配，一个是黑龙江省的，一个是广东省的，但是目前只会返回第一个；
还有如果只输入一个镇，返回的只有null，这里该怎么改呢？

**Comment by IceMimosa** [comment]
1. 输入“南山区”，目前不支持多地区返回，优先返回第一个匹配的
2. 输入镇的话，信息量太少，只能返回null。
你期望返回什么呢，麻烦举个具体的例子
