### ISSUE TITLE
怎么生成国标地址库

### ISSUE THREAD

**Issue by xun404** [bitlap/geocoding#7]
有对应的工具方法么？想生成一份国标的，求助下大佬

**Comment by IceMimosa** [comment]
国际的地址长啥样子，我猜估计支持不了。

**Comment by xun404** [comment]
> 国际的地址长啥样子，我猜估计支持不了。

不是国际，是国标；现在用的 region.dat 是淘宝的想换成国标的，但是region.dat压缩后的原始数据不知道是否有工具，或者是否可以提供下结构参考一下

**Comment by IceMimosa** [comment]
看一下这个代码读取，直接decode出来就是大的json。

https://github.com/IceMimosa/geocoding/blob/master/src/main/java/io/patamon/geocoding/core/impl/DefaultRegoinCache.kt

**Comment by IceMimosa** [comment]
Release 1.1.3
