### ISSUE TITLE
removeRedundancy时误删有用的POI字符串

### ISSUE THREAD

**Issue by futureer** [bitlap/geocoding#9]
你好，
    感谢开源这么有用的工具。
    `Geocoding.normalizing` 这个API，在匹配完四级行政区之后，为了处理省市区重复书写的情况，`removeRedundancy()` 函数会继续移除能够解析到的省市区/县 乡镇/街道 及其之前的字符串，方便专心处理POI字符串。 但当POI字符串中出现了正常的地名字符串后（如 浙江省杭州市西湖区中国建设银河西湖支行），`removeRedundancy()` 函数会错误的将 POI中的信息删除，只剩下“支行”。

举个栗子：

```
print(Geocoding.normalizing("浙江省杭州市西湖区中国建设银河西湖支行"))

[Out]
Address(
	provinceId=330000000000, province=浙江省, 
	cityId=330100000000, city=杭州市, 
	districtId=330106000000, district=西湖区, 
	streetId=null, street=null, 
	townId=null, town=null, 
	villageId=null, village=null, 
	road=null, 
	roadNum=null, 
	buildingNum=null, 
	text=支行
)
```

**Comment by IceMimosa** [comment]
感谢反馈和问题定位，方法有个if判断错了。😂
